---

- name: install debian dependecies
  apt:
    name: "{{ item }}"
    state: present
  with_items: harstorage_debian_pkgs

- name: install python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: harstorage_python_pkgs

- name: create directories
  file:
    path: "{{ item }}"
    owner: "{{ harstorage_user }}"
    group: "{{ harstorage_user }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ harstorage_etc }}"
    - "{{ harstorage_code_dir }}"

- name: setup the harstorage development.ini file
  template:
    src: '.{{ harstorage_etc }}/development.ini.j2'
    dest: '{{ harstorage_etc }}/development.ini'
    owner: '{{ harstorage_user }}'
    group: '{{ harstorage_user }}'
    mode: 0644

- name: install harstorage
  command: "/usr/bin/python ./setup.py install"
  args:
    chdir: "{{ harstorage_code_dir }}"

- name: apply config
  command: "/usr/bin/paster setup-app {{ harstorage_etc }}/development.ini"
  args:
    chdir: "{{ harstorage_code_dir }}"

- name: run harstorage
  command: "{{ harstorage_venv_dir }}/bin/paster serve --daemon {{ harstorage_venv_dir }}/{{ harstorage_etc }}/production.ini"
